USE MASTER
CREATE DATABASE QLDA
USE QLDA
go 

CREATE TABLE PHANCONG
(
MaNV varchar(9) NOT NULL,
MaDA varchar(2) NOT NULL,
ThoiGian numeric(18,0) NOT NULL
)

CREATE TABLE DEAN
(
MaDA varchar(2) PRIMARY KEY,
TenDA nvarchar(50) NOT NULL,
DDiemDA varchar(20) NOT NULL
)

CREATE TABLE NHANVIEN
(
MaNV varchar(9) PRIMARY KEY,
HoNV nvarchar(15) NOT NULL,
TenLot nvarchar(30) NOT NULL,
TenNV nvarchar(30) NOT NULL,
NgSinh smalldatetime NULL,
DiaChi nvarchar(150) NOT NULL,
Phai nvarchar(3) NOT NULL,
Luong numeric(18,0) NULL,
Phong varchar(2) NOT NULL
)

CREATE TABLE PHONGBAN
(
MaPhg varchar(2) PRIMARY KEY,
TenPhg nvarchar(20) NOT NULL
)

CREATE TABLE THANNHAN
(
MaNV varchar(9) NOT NULL,
TenTN varchar(20) NOT NULL,
NgaySinh smalldatetime NULL,
Phai varchar(3) NOT NULL,
QuanHe varchar(15) NOT NULL
)

ALTER TABLE PHANCONG
ADD CONSTRAINT PHANCONG_pk PRIMARY KEY(MaNV,MaDA);

ALTER TABLE THANNHAN
ADD CONSTRAINT THANNHAN_pk PRIMARY KEY(MaNV,TenTN);

ALTER TABLE PHANCONG
ADD  CONSTRAINT PB_MaDA_FK FOREIGN KEY (MaDA) REFERENCES DEAN (MaDA)

ALTER TABLE PHANCONG
ADD  CONSTRAINT PB_MaNV_FK FOREIGN KEY (MaNV) REFERENCES NHANVIEN (MaNV)

ALTER TABLE NHANVIEN
ADD  CONSTRAINT PB_PHONG_FK FOREIGN KEY (PHONG) REFERENCES PHONGBAN (MaPhg)

ALTER TABLE THANNHAN
ADD  CONSTRAINT THANNHAN_MaNV_FK FOREIGN KEY (MaNV) REFERENCES NHANVIEN (MaNV)

BEGIN /** NHANVIEN **/
	ALTER TABLE NHANVIEN
	NOCHECK CONSTRAINT ALL
	INSERT INTO NHANVIEN (MaNV, HoNV, TenLot, TenNv, NgSinh, DiaChi, Phai, LUONG,Phong)
	VALUES (N'123',N'Đinh', N'Bá', N'Tiến', '02/27/1982', N'Mộ Đức', N'Nam', null, 5)
	INSERT INTO NHANVIEN (MaNV, HoNV, TenLot, TenNv, NgSinh, DiaChi, Phai, LUONG,Phong)
    VALUES (N'234',N'Nguyễn', N'Thanh', N'Tùng', '08/12/1956', N'Sơn Tịng', N'Nam', null, 5)
	INSERT INTO NHANVIEN (MaNV, HoNV, TenLot, TenNv, NgSinh, DiaChi, Phai, LUONG,Phong)
	VALUES (N'345',N'Bùi', N'Thuý', N'Vũ', null, N'Từ Nghĩa', N'Nữ', null, 4)
	INSERT INTO NHANVIEN (MaNV, HoNV, TenLot, TenNv, NgSinh, DiaChi, Phai, LUONG,Phong)
	VALUES (N'456',N'Lê', N'Thị', N'Nhàn', '07/12/1962', N'Mộ Đức', N'Nữ', null, 4)
	INSERT INTO NHANVIEN (MaNV, HoNV, TenLot, TenNv, NgSinh, DiaChi, Phai, LUONG,Phong)
	VALUES (N'567',N'Nguyễn', N'Thị Mạnh', N'Hùng', '03/25/1985', N'Sơn Tịnh', N'Nam', null, 5)
	INSERT INTO NHANVIEN (MaNV, HoNV, TenLot, TenNv, NgSinh, DiaChi, Phai, LUONG,Phong)
	VALUES (N'678',N'Trần', N'Hồng', N'Quang', null, N'Bình Sơn', N'Nam', null, 5)
	INSERT INTO NHANVIEN (MaNV, HoNV, TenLot, TenNv, NgSinh, DiaChi, Phai, LUONG,Phong)
	VALUES (N'789',N'Trần', N'Thanh', N'Tâm', '06/17/1972', N'Tp Quảng Ngãi', N'Nam', null, 5)
	INSERT INTO NHANVIEN (MaNV, HoNV, TenLot, TenNv, NgSinh, DiaChi, Phai, LUONG,Phong)
	VALUES (N'890',N'Cao', N'Thanh', N'Huyền', null, N'Tự Nghĩa', N'Nữ', null, 1)
	INSERT INTO NHANVIEN (MaNV, HoNV, TenLot, TenNv, NgSinh, DiaChi, Phai, LUONG,Phong)
	VALUES (N'901',N'Vương', N'Ngọc', N'Quyền', '12/12/1987', N'Mộ Đức', N'Nam', null, 1)
END
BEGIN /** PHONGBAN **/
	ALTER TABLE PHONGBAN
	NOCHECK CONSTRAINT ALL
	INSERT INTO PHONGBAN (MAPHG, TENPHG)
	VALUES ('1',N'QUẢN LÝ')
	INSERT INTO PHONGBAN (MAPHG,TENPHG)
	VALUES('4',N'ĐIỀU HÀNH')
	INSERT INTO PHONGBAN (MAPHG,TENPHG)
	VALUES('5',N'NGHIÊN CỨU')
	ALTER TABLE PHONGBAN
	CHECK CONSTRAINT ALL
END

BEGIN /** DEAN **/
	ALTER TABLE DEAN
	NOCHECK CONSTRAINT ALL
	INSERT INTO DEAN (MADA, TENDA, DDIEMDA)
	VALUES (1,N'Nâng cao chất lượng muối',N'Sa Huỳnh')
	INSERT INTO DEAN (MADA, TENDA, DDIEMDA)
	VALUES (10,N'Xây dựng nhà máy chế biến thủy sản',N'Dung Quất')
	INSERT INTO DEAN (MADA, TENDA, DDIEMDA)
	VALUES (2,N'Phát triển hạ tầng mạng',N'Tp Quãng Ngãi')
	INSERT INTO DEAN (MADA, TENDA, DDIEMDA)
	VALUES (20,N'Truyền tải cáp quang',N'Tp Quãng Ngãi')
	INSERT INTO DEAN (MADA, TENDA, DDIEMDA)
	VALUES (2,N'Tin học hóa trường học',N'Ba Tơ')
	INSERT INTO DEAN (MADA, TENDA, DDIEMDA)
	VALUES (30,N'Đào tạo nhân lực',N'Tịnh Phong')
	ALTER TABLE DEAN
	CHECK CONSTRAINT ALL
END

BEGIN /** THANNHAN **/
	ALTER TABLE THANNHAN
	NOCHECK CONSTRAINT ALL
	INSERT INTO THANNHAN (MANV, TENTN, NgaySinh,PHAI, QUANHE)
	VALUES ('123', N'Châu', '10/30/2005',N'Nữ', N'Con gái')
	INSERT INTO THANNHAN (MANV, TENTN, NgaySinh,PHAI, QUANHE)
	VALUES ('123', N'Duy', '10/25/2005',N'Nam', N'Con trai')
	INSERT INTO THANNHAN (MANV, TENTN, NgaySinh,PHAI, QUANHE)
	VALUES ('123', N'Phương','10/30/1985',N'Nữ', N'Vợ chồng')
	INSERT INTO THANNHAN (MANV, TENTN, NgaySinh,PHAI, QUANHE)
	VALUES ('234', N'Thanh', '04/05/1980',N'Nữ', N'Con gái')
	INSERT INTO THANNHAN (MANV, TENTN, NgaySinh,PHAI, QUANHE)
	VALUES ('345', N'Dương', '10/30/1956',N'Nam', N'Vợ chồng')
	INSERT INTO THANNHAN (MANV, TENTN, NgaySinh,PHAI, QUANHE)
	VALUES ('345', N'Khang', '10/25/1982',N'Nam', N'Con trai')
	INSERT INTO THANNHAN (MANV, TENTN, NgaySinh,PHAI, QUANHE)
	VALUES ('456', N'Hùng', '01/01/1987',N'Nam', N'Con trai')
	INSERT INTO THANNHAN	(MANV, TENTN, NgaySinh,PHAI, QUANHE)
	VALUES ('901', N'Thương', '04/05/1988',N'Nữ', N'Vợ chồng')
	ALTER TABLE THANNHAN
	CHECK CONSTRAINT ALL
END
BEGIN /** PHANCONG **/
	ALTER TABLE PHANCONG
	NOCHECK CONSTRAINT ALL
	INSERT INTO PHANCONG (MANV, MADA, THOIGIAN)
	VALUES ('123',1,33)
	INSERT INTO PHANCONG (MANV, MADA, THOIGIAN)
	VALUES ('123',2,8)
	INSERT INTO PHANCONG (MANV, MADA, THOIGIAN)
	VALUES ('345',10,10)
	INSERT INTO PHANCONG (MANV, MADA, THOIGIAN)
	VALUES ('345',20,10)
	INSERT INTO PHANCONG (MANV, MADA, THOIGIAN)
	VALUES ('345',3,10)
	INSERT INTO PHANCONG (MANV, MADA, THOIGIAN)
	VALUES ('456',1,20)
	INSERT INTO PHANCONG (MANV, MADA, THOIGIAN)
	VALUES ('456',2,20)
	INSERT INTO PHANCONG (MANV, MADA, THOIGIAN)
	VALUES ('678',3,40)
	INSERT INTO PHANCONG (MANV, MADA, THOIGIAN)
	VALUES ('789',10,35)
	INSERT INTO PHANCONG (MANV, MADA, THOIGIAN)
	VALUES ('789',20,30)
	INSERT INTO PHANCONG (MANV, MADA, THOIGIAN)
	VALUES ('789',30,5)
	ALTER TABLE PHANCONG
	CHECK CONSTRAINT ALL
END

